export enum TipoDeDocumento {
    CEDULA_DE_CIUDADANA="CEDULA_DE_CIUDADANA",
    TARJETA_DE_IDENTIDAD="TARJETA_DE_IDENTIDAD=",
    PASAPORTE="PASAPORTE",
    CEDULA_DE_EXTRANJERIA="CEDULA_DE_EXTRANJERIA"
}